export const LOCATIONS = ['Fridge', 'Freezer', 'Pantry'];

export const CATEGORIES = [
  'Produce', 'Dairy', 'Meat', 'Grains', 'Condiments',
  'Beverages', 'Bakery', 'Pantry & Dry', 'Frozen', 'Other',
];

const today = new Date();
function dateKey(offset = 0) {
  const d = new Date(today);
  d.setDate(d.getDate() + offset);
  return d.toISOString().split('T')[0];
}

export const INITIAL_FRIDGE_ITEMS = [
  { id: 'f1', name: 'Chicken Breast', qty: 2, unit: 'pcs', location: 'Fridge', category: 'Meat', expiryDays: 5, emoji: '🍗', threshold: 1 },
  { id: 'f2', name: 'Whole Milk', qty: 1, unit: 'L', location: 'Fridge', category: 'Dairy', expiryDays: 5, emoji: '🥛', threshold: 1 },
  { id: 'f3', name: 'Eggs', qty: 8, unit: 'pcs', location: 'Fridge', category: 'Dairy', expiryDays: 14, emoji: '🥚', threshold: 4 },
  { id: 'f4', name: 'Spinach', qty: 1, unit: 'bag', location: 'Fridge', category: 'Produce', expiryDays: 6, emoji: '🥬', threshold: 1 },
  { id: 'f5', name: 'Greek Yogurt', qty: 2, unit: 'cups', location: 'Fridge', category: 'Dairy', expiryDays: 8, emoji: '🥄', threshold: 1 },
  { id: 'f6', name: 'Bell Peppers', qty: 3, unit: 'pcs', location: 'Fridge', category: 'Produce', expiryDays: 6, emoji: '🫑', threshold: 2 },
  { id: 'f7', name: 'Cheddar Cheese', qty: 200, unit: 'g', location: 'Fridge', category: 'Dairy', expiryDays: 18, emoji: '🧀', threshold: 100 },
  { id: 'f8', name: 'Salmon Fillet', qty: 1, unit: 'pc', location: 'Freezer', category: 'Meat', expiryDays: 30, emoji: '🐟', threshold: 1 },
  { id: 'f9', name: 'Frozen Peas', qty: 500, unit: 'g', location: 'Freezer', category: 'Frozen', expiryDays: 90, emoji: '🟢', threshold: 200 },
  { id: 'f10', name: 'Ice Cream', qty: 1, unit: 'tub', location: 'Freezer', category: 'Frozen', expiryDays: 60, emoji: '🍨', threshold: 1 },
  { id: 'f11', name: 'Rice', qty: 2, unit: 'kg', location: 'Pantry', category: 'Grains', expiryDays: 365, emoji: '🍚', threshold: 1 },
  { id: 'f12', name: 'Olive Oil', qty: 750, unit: 'ml', location: 'Pantry', category: 'Condiments', expiryDays: 180, emoji: '🫒', threshold: 200 },
  { id: 'f13', name: 'Pasta', qty: 500, unit: 'g', location: 'Pantry', category: 'Grains', expiryDays: 365, emoji: '🍝', threshold: 250 },
  { id: 'f14', name: 'Sourdough Bread', qty: 1, unit: 'loaf', location: 'Pantry', category: 'Bakery', expiryDays: 4, emoji: '🍞', threshold: 1 },
  { id: 'f15', name: 'Bananas', qty: 4, unit: 'pcs', location: 'Pantry', category: 'Produce', expiryDays: 7, emoji: '🍌', threshold: 2 },
  { id: 'f16', name: 'Strawberries', qty: 250, unit: 'g', location: 'Fridge', category: 'Produce', expiryDays: 2, emoji: '🍓', threshold: 100 },
  { id: 'f17', name: 'Leftover Pasta', qty: 1, unit: 'container', location: 'Fridge', category: 'Other', expiryDays: 1, emoji: '🍝', threshold: 1 },
  { id: 'f18', name: 'Fresh Basil', qty: 1, unit: 'bunch', location: 'Fridge', category: 'Produce', expiryDays: 2, emoji: '🌿', threshold: 1 },
  { id: 'f19', name: 'Cooked Rice', qty: 1, unit: 'container', location: 'Fridge', category: 'Other', expiryDays: 1, emoji: '🍚', threshold: 1 },
  { id: 'f20', name: 'Cut Watermelon', qty: 1, unit: 'container', location: 'Fridge', category: 'Produce', expiryDays: 2, emoji: '🍉', threshold: 1 },
  { id: 'f21', name: 'Opened Hummus', qty: 150, unit: 'g', location: 'Fridge', category: 'Other', expiryDays: 2, emoji: '🫘', threshold: 50 },
  { id: 'f22', name: 'Sliced Turkey', qty: 100, unit: 'g', location: 'Fridge', category: 'Meat', expiryDays: 1, emoji: '🦃', threshold: 50 },
  { id: 'f23', name: 'Avocado', qty: 2, unit: 'pcs', location: 'Fridge', category: 'Produce', expiryDays: 2, emoji: '🥑', threshold: 1 },
  { id: 'f24', name: 'Leftover Soup', qty: 1, unit: 'container', location: 'Fridge', category: 'Other', expiryDays: 1, emoji: '🍲', threshold: 1 },
  { id: 'f25', name: 'Greek Yogurt Cup', qty: 1, unit: 'cup', location: 'Fridge', category: 'Dairy', expiryDays: 2, emoji: '🥄', threshold: 1 },
];

export const INITIAL_SHOPPING_LIST = [
  { id: 's1', name: 'Tomatoes', qty: 6, unit: 'pcs', category: 'Produce', checked: false, source: 'recipe', sourceLabel: 'Pasta Sauce' },
  { id: 's2', name: 'Garlic', qty: 1, unit: 'head', category: 'Produce', checked: false, source: 'manual', sourceLabel: null },
  { id: 's3', name: 'Heavy Cream', qty: 250, unit: 'ml', category: 'Dairy', checked: false, source: 'recipe', sourceLabel: 'Carbonara' },
  { id: 's4', name: 'Parmesan', qty: 100, unit: 'g', category: 'Dairy', checked: true, source: 'manual', sourceLabel: null },
  { id: 's5', name: 'Avocados', qty: 3, unit: 'pcs', category: 'Produce', checked: false, source: 'lowstock', sourceLabel: 'Low stock' },
];

export const INITIAL_MEAL_PLAN = {
  [dateKey(0)]: {
    breakfast: { name: 'Greek Yogurt Bowl', emoji: '🥄', time: '8:00 AM' },
    lunch: null,
    dinner: { name: 'Chicken Stir Fry', emoji: '🍗', time: '7:00 PM' },
  },
  [dateKey(1)]: {
    breakfast: null,
    lunch: { name: 'Spinach Salad', emoji: '🥗', time: '12:30 PM' },
    dinner: { name: 'Salmon & Rice', emoji: '🐟', time: '7:30 PM' },
  },
  [dateKey(2)]: {
    breakfast: { name: 'Banana Pancakes', emoji: '🥞', time: '9:00 AM' },
    lunch: null,
    dinner: null,
  },
  [dateKey(3)]: {
    breakfast: null,
    lunch: null,
    dinner: { name: 'Pasta Carbonara', emoji: '🍝', time: '7:00 PM' },
  },
  [dateKey(4)]: {
    breakfast: null,
    lunch: null,
    dinner: null,
  },
  [dateKey(5)]: {
    breakfast: null,
    lunch: { name: 'Cheese Sandwich', emoji: '🧀', time: '1:00 PM' },
    dinner: null,
  },
  [dateKey(6)]: {
    breakfast: null,
    lunch: null,
    dinner: null,
  },
};

export const INITIAL_ACTIVITY = [
  { id: 'a1', text: 'Added 6 items from Woolworths receipt', time: '2 hours ago', icon: '🧾', date: dateKey(0) },
  { id: 'a2', text: 'Cooked Chicken Stir Fry', time: '1 day ago', icon: '👨‍🍳', date: dateKey(-1) },
  { id: 'a3', text: 'Added Tomatoes to shopping list', time: '1 day ago', icon: '🛒', date: dateKey(-1) },
  { id: 'a4', text: 'Generated 3 recipes from kitchen', time: '2 days ago', icon: '✨', date: dateKey(-2) },
];

export const MOCK_RECIPES = [
  {
    id: 'r1',
    name: 'Chicken & Spinach Stir Fry',
    emoji: '🥘',
    time: '25 min',
    difficulty: 'Easy',
    servings: 2,
    description: 'Quick and healthy stir fry using chicken and fresh spinach from your kitchen.',
    usesExpiring: true,
    cuisineType: 'Asian',
    ingredients: [
      { name: 'Chicken Breast', qty: '2 pcs', fromFridge: true },
      { name: 'Spinach', qty: '1 bag', fromFridge: true },
      { name: 'Bell Peppers', qty: '2 pcs', fromFridge: true },
      { name: 'Rice', qty: '1 cup', fromFridge: true },
      { name: 'Soy Sauce', qty: '2 tbsp', fromFridge: false },
      { name: 'Sesame Oil', qty: '1 tbsp', fromFridge: false },
    ],
    steps: [
      { instruction: 'Cook rice according to package instructions.', timerSeconds: 900 },
      { instruction: 'Slice chicken breast into thin strips and season with salt and pepper.', timerSeconds: null },
      { instruction: 'Heat sesame oil in a wok over high heat.', timerSeconds: null },
      { instruction: 'Stir fry chicken until golden brown, about 5 minutes.', timerSeconds: 300 },
      { instruction: 'Add sliced bell peppers and cook for 3 minutes.', timerSeconds: 180 },
      { instruction: 'Add spinach and soy sauce, toss until wilted.', timerSeconds: 60 },
      { instruction: 'Serve over rice.', timerSeconds: null },
    ],
    nutrition: { calories: 420, protein: 38, carbs: 42, fat: 12 },
  },
  {
    id: 'r2',
    name: 'Banana Bread',
    emoji: '🍌',
    time: '55 min',
    difficulty: 'Easy',
    servings: 8,
    description: 'Use up those ripe bananas before they expire! Moist and delicious.',
    usesExpiring: true,
    cuisineType: 'American',
    ingredients: [
      { name: 'Bananas', qty: '3 pcs', fromFridge: true },
      { name: 'Eggs', qty: '2 pcs', fromFridge: true },
      { name: 'Whole Milk', qty: '60 ml', fromFridge: true },
      { name: 'Flour', qty: '280 g', fromFridge: false },
      { name: 'Sugar', qty: '150 g', fromFridge: false },
      { name: 'Butter', qty: '115 g', fromFridge: false },
    ],
    steps: [
      { instruction: 'Preheat oven to 175°C (350°F). Grease a loaf pan.', timerSeconds: null },
      { instruction: 'Mash bananas in a bowl until smooth.', timerSeconds: null },
      { instruction: 'Mix in melted butter, sugar, egg, and milk.', timerSeconds: null },
      { instruction: 'Fold in flour and a pinch of salt until just combined.', timerSeconds: null },
      { instruction: 'Pour batter into prepared loaf pan.', timerSeconds: null },
      { instruction: 'Bake for 50 minutes until a toothpick comes out clean.', timerSeconds: 3000 },
      { instruction: 'Cool for 10 minutes before slicing.', timerSeconds: 600 },
    ],
    nutrition: { calories: 290, protein: 5, carbs: 48, fat: 10 },
  },
  {
    id: 'r3',
    name: 'Creamy Pasta Carbonara',
    emoji: '🍝',
    time: '20 min',
    difficulty: 'Medium',
    servings: 2,
    description: 'Classic Italian carbonara with a rich, silky egg sauce.',
    usesExpiring: false,
    cuisineType: 'Italian',
    ingredients: [
      { name: 'Pasta', qty: '250 g', fromFridge: true },
      { name: 'Eggs', qty: '3 pcs', fromFridge: true },
      { name: 'Cheddar Cheese', qty: '100 g', fromFridge: true },
      { name: 'Heavy Cream', qty: '60 ml', fromFridge: false },
      { name: 'Bacon', qty: '150 g', fromFridge: false },
      { name: 'Black Pepper', qty: 'to taste', fromFridge: false },
    ],
    steps: [
      { instruction: 'Bring a large pot of salted water to boil. Cook pasta al dente.', timerSeconds: 600 },
      { instruction: 'While pasta cooks, fry bacon until crispy. Set aside.', timerSeconds: 300 },
      { instruction: 'Whisk eggs, grated cheese, and cream together in a bowl.', timerSeconds: null },
      { instruction: 'Drain pasta, reserving 1 cup of pasta water.', timerSeconds: null },
      { instruction: 'Toss hot pasta with egg mixture off the heat, adding pasta water to loosen.', timerSeconds: null },
      { instruction: 'Top with crispy bacon and plenty of black pepper.', timerSeconds: null },
    ],
    nutrition: { calories: 580, protein: 28, carbs: 62, fat: 24 },
  },
  {
    id: 'r4',
    name: 'Strawberry Banana Smoothie',
    emoji: '🍓',
    time: '5 min',
    difficulty: 'Easy',
    servings: 2,
    description: 'Creamy and refreshing smoothie using up strawberries and bananas.',
    usesExpiring: true,
    cuisineType: 'American',
    ingredients: [
      { name: 'Strawberries', qty: '150 g', fromFridge: true },
      { name: 'Bananas', qty: '2 pcs', fromFridge: true },
      { name: 'Greek Yogurt', qty: '1 cup', fromFridge: true },
      { name: 'Whole Milk', qty: '200 ml', fromFridge: true },
      { name: 'Honey', qty: '1 tbsp', fromFridge: false },
    ],
    steps: [
      { instruction: 'Slice bananas and hull strawberries.', timerSeconds: null },
      { instruction: 'Add all ingredients to a blender.', timerSeconds: null },
      { instruction: 'Blend on high until smooth and creamy, about 30 seconds.', timerSeconds: 30 },
      { instruction: 'Pour into glasses and serve immediately.', timerSeconds: null },
    ],
    nutrition: { calories: 210, protein: 8, carbs: 38, fat: 4 },
  },
  {
    id: 'r5',
    name: 'Avocado Egg Toast',
    emoji: '🥑',
    time: '10 min',
    difficulty: 'Easy',
    servings: 1,
    description: 'Creamy avocado on toasted sourdough topped with a perfectly fried egg.',
    usesExpiring: true,
    cuisineType: 'American',
    ingredients: [
      { name: 'Avocado', qty: '1 pc', fromFridge: true },
      { name: 'Eggs', qty: '1 pc', fromFridge: true },
      { name: 'Sourdough Bread', qty: '2 slices', fromFridge: true },
      { name: 'Olive Oil', qty: '1 tsp', fromFridge: true },
      { name: 'Chilli Flakes', qty: 'pinch', fromFridge: false },
      { name: 'Salt & Pepper', qty: 'to taste', fromFridge: false },
    ],
    steps: [
      { instruction: 'Toast sourdough slices until golden.', timerSeconds: 180 },
      { instruction: 'Halve avocado, remove seed, and scoop flesh into a bowl. Mash with a fork.', timerSeconds: null },
      { instruction: 'Season avocado with salt, pepper, and a squeeze of lemon if available.', timerSeconds: null },
      { instruction: 'Fry egg in olive oil to your liking, about 3 minutes for runny yolk.', timerSeconds: 180 },
      { instruction: 'Spread avocado on toast, top with egg and chilli flakes.', timerSeconds: null },
    ],
    nutrition: { calories: 360, protein: 12, carbs: 30, fat: 22 },
  },
  {
    id: 'r6',
    name: 'Turkey Avocado Sandwich',
    emoji: '🥪',
    time: '5 min',
    difficulty: 'Easy',
    servings: 1,
    description: 'Quick and satisfying sandwich using sliced turkey and creamy avocado.',
    usesExpiring: true,
    cuisineType: 'American',
    ingredients: [
      { name: 'Sliced Turkey', qty: '100 g', fromFridge: true },
      { name: 'Avocado', qty: '1 pc', fromFridge: true },
      { name: 'Sourdough Bread', qty: '2 slices', fromFridge: true },
      { name: 'Cheddar Cheese', qty: '30 g', fromFridge: true },
      { name: 'Mustard', qty: '1 tsp', fromFridge: false },
    ],
    steps: [
      { instruction: 'Slice avocado thinly.', timerSeconds: null },
      { instruction: 'Spread mustard on one slice of bread.', timerSeconds: null },
      { instruction: 'Layer turkey, avocado, and cheese on the bread.', timerSeconds: null },
      { instruction: 'Top with the second slice and press gently. Serve.', timerSeconds: null },
    ],
    nutrition: { calories: 480, protein: 30, carbs: 34, fat: 24 },
  },
  {
    id: 'r7',
    name: 'Salmon Fried Rice',
    emoji: '🐟',
    time: '15 min',
    difficulty: 'Medium',
    servings: 2,
    description: 'Quick fried rice using leftover cooked rice, salmon, and frozen peas.',
    usesExpiring: true,
    cuisineType: 'Asian',
    ingredients: [
      { name: 'Salmon Fillet', qty: '1 pc', fromFridge: true },
      { name: 'Cooked Rice', qty: '1 container', fromFridge: true },
      { name: 'Eggs', qty: '2 pcs', fromFridge: true },
      { name: 'Frozen Peas', qty: '100 g', fromFridge: true },
      { name: 'Soy Sauce', qty: '2 tbsp', fromFridge: false },
      { name: 'Sesame Oil', qty: '1 tsp', fromFridge: false },
    ],
    steps: [
      { instruction: 'Flake salmon into chunks and season with salt and pepper.', timerSeconds: null },
      { instruction: 'Heat oil in a wok over high heat. Cook salmon for 3 minutes then set aside.', timerSeconds: 180 },
      { instruction: 'Scramble eggs in the same wok, then push to the side.', timerSeconds: 60 },
      { instruction: 'Add cooked rice and peas, stir-fry for 3 minutes.', timerSeconds: 180 },
      { instruction: 'Return salmon, drizzle soy sauce and sesame oil, toss to combine.', timerSeconds: null },
    ],
    nutrition: { calories: 450, protein: 34, carbs: 44, fat: 14 },
  },
  {
    id: 'r8',
    name: 'Cheese & Spinach Omelette',
    emoji: '🍳',
    time: '10 min',
    difficulty: 'Easy',
    servings: 1,
    description: 'Fluffy omelette packed with fresh spinach and melted cheddar.',
    usesExpiring: false,
    cuisineType: 'French',
    ingredients: [
      { name: 'Eggs', qty: '3 pcs', fromFridge: true },
      { name: 'Spinach', qty: 'handful', fromFridge: true },
      { name: 'Cheddar Cheese', qty: '40 g', fromFridge: true },
      { name: 'Whole Milk', qty: '2 tbsp', fromFridge: true },
      { name: 'Butter', qty: '1 tsp', fromFridge: false },
      { name: 'Salt & Pepper', qty: 'to taste', fromFridge: false },
    ],
    steps: [
      { instruction: 'Whisk eggs with milk, salt, and pepper until fluffy.', timerSeconds: null },
      { instruction: 'Melt butter in a non-stick pan over medium heat.', timerSeconds: null },
      { instruction: 'Pour in egg mixture and let set on the bottom, about 2 minutes.', timerSeconds: 120 },
      { instruction: 'Add spinach and grated cheese to one half.', timerSeconds: null },
      { instruction: 'Fold omelette and cook 1 more minute until cheese melts.', timerSeconds: 60 },
    ],
    nutrition: { calories: 320, protein: 24, carbs: 4, fat: 22 },
  },
  {
    id: 'r9',
    name: 'Basil Pasta Aglio e Olio',
    emoji: '🌿',
    time: '20 min',
    difficulty: 'Easy',
    servings: 2,
    description: 'Simple and fragrant pasta with fresh basil, garlic, and olive oil.',
    usesExpiring: true,
    cuisineType: 'Italian',
    ingredients: [
      { name: 'Pasta', qty: '250 g', fromFridge: true },
      { name: 'Fresh Basil', qty: '1 bunch', fromFridge: true },
      { name: 'Olive Oil', qty: '4 tbsp', fromFridge: true },
      { name: 'Cheddar Cheese', qty: '50 g', fromFridge: true },
      { name: 'Garlic', qty: '4 cloves', fromFridge: false },
      { name: 'Chilli Flakes', qty: 'pinch', fromFridge: false },
    ],
    steps: [
      { instruction: 'Cook pasta in salted boiling water until al dente.', timerSeconds: 600 },
      { instruction: 'While pasta cooks, gently warm olive oil with garlic and chilli flakes.', timerSeconds: 180 },
      { instruction: 'Drain pasta, reserving ½ cup pasta water.', timerSeconds: null },
      { instruction: 'Toss pasta in the garlic oil, adding pasta water to emulsify.', timerSeconds: null },
      { instruction: 'Tear fresh basil leaves over the top and finish with grated cheese.', timerSeconds: null },
    ],
    nutrition: { calories: 490, protein: 14, carbs: 66, fat: 18 },
  },
  {
    id: 'r10',
    name: 'Hummus Veggie Rice Bowl',
    emoji: '🫘',
    time: '10 min',
    difficulty: 'Easy',
    servings: 1,
    description: 'Wholesome bowl using leftover hummus, cooked rice, and fresh veggies.',
    usesExpiring: true,
    cuisineType: 'Mediterranean',
    ingredients: [
      { name: 'Opened Hummus', qty: '150 g', fromFridge: true },
      { name: 'Cooked Rice', qty: '1 container', fromFridge: true },
      { name: 'Bell Peppers', qty: '1 pc', fromFridge: true },
      { name: 'Spinach', qty: 'handful', fromFridge: true },
      { name: 'Olive Oil', qty: '1 tbsp', fromFridge: true },
      { name: 'Lemon Juice', qty: '1 tbsp', fromFridge: false },
      { name: 'Paprika', qty: 'pinch', fromFridge: false },
    ],
    steps: [
      { instruction: 'Warm the cooked rice in a pan or microwave.', timerSeconds: 120 },
      { instruction: 'Slice bell peppers into strips.', timerSeconds: null },
      { instruction: 'Arrange rice in a bowl, top with a scoop of hummus.', timerSeconds: null },
      { instruction: 'Add spinach, bell peppers, and drizzle with olive oil and lemon juice.', timerSeconds: null },
      { instruction: 'Dust with paprika and serve.', timerSeconds: null },
    ],
    nutrition: { calories: 380, protein: 12, carbs: 52, fat: 14 },
  },
  {
    id: 'r11',
    name: 'Chicken Rice Bowl',
    emoji: '🍗',
    time: '30 min',
    difficulty: 'Easy',
    servings: 2,
    description: 'Simple and filling rice bowl with juicy chicken, peppers, and spinach.',
    usesExpiring: false,
    cuisineType: 'American',
    ingredients: [
      { name: 'Chicken Breast', qty: '2 pcs', fromFridge: true },
      { name: 'Rice', qty: '1 cup', fromFridge: true },
      { name: 'Bell Peppers', qty: '2 pcs', fromFridge: true },
      { name: 'Spinach', qty: 'handful', fromFridge: true },
      { name: 'Olive Oil', qty: '2 tbsp', fromFridge: true },
      { name: 'Salt & Pepper', qty: 'to taste', fromFridge: false },
    ],
    steps: [
      { instruction: 'Cook rice according to package instructions.', timerSeconds: 900 },
      { instruction: 'Season chicken with salt and pepper.', timerSeconds: null },
      { instruction: 'Heat olive oil and cook chicken for 6 minutes each side.', timerSeconds: 360 },
      { instruction: 'Rest chicken 5 minutes, then slice.', timerSeconds: 300 },
      { instruction: 'Sauté bell peppers and spinach in the same pan for 3 minutes.', timerSeconds: 180 },
      { instruction: 'Assemble bowl with rice, vegetables, and sliced chicken.', timerSeconds: null },
    ],
    nutrition: { calories: 440, protein: 40, carbs: 42, fat: 12 },
  },
  {
    id: 'r12',
    name: 'Banana Berry Yogurt Parfait',
    emoji: '🍓',
    time: '5 min',
    difficulty: 'Easy',
    servings: 1,
    description: 'Layered parfait with creamy Greek yogurt, fresh strawberries, and banana.',
    usesExpiring: true,
    cuisineType: 'American',
    ingredients: [
      { name: 'Greek Yogurt', qty: '1 cup', fromFridge: true },
      { name: 'Strawberries', qty: '100 g', fromFridge: true },
      { name: 'Bananas', qty: '1 pc', fromFridge: true },
      { name: 'Honey', qty: '1 tsp', fromFridge: false },
    ],
    steps: [
      { instruction: 'Hull and slice strawberries. Slice banana.', timerSeconds: null },
      { instruction: 'Spoon half the yogurt into a glass.', timerSeconds: null },
      { instruction: 'Layer strawberries and banana slices on top.', timerSeconds: null },
      { instruction: 'Add remaining yogurt and top with more fruit and a drizzle of honey.', timerSeconds: null },
    ],
    nutrition: { calories: 240, protein: 14, carbs: 38, fat: 4 },
  },
  {
    id: 'r13',
    name: 'Leftover Pasta Frittata',
    emoji: '🍝',
    time: '15 min',
    difficulty: 'Easy',
    servings: 2,
    description: 'Brilliant way to use up leftover pasta — baked into a cheesy egg frittata.',
    usesExpiring: true,
    cuisineType: 'Italian',
    ingredients: [
      { name: 'Leftover Pasta', qty: '1 container', fromFridge: true },
      { name: 'Eggs', qty: '4 pcs', fromFridge: true },
      { name: 'Cheddar Cheese', qty: '60 g', fromFridge: true },
      { name: 'Spinach', qty: 'handful', fromFridge: true },
      { name: 'Whole Milk', qty: '3 tbsp', fromFridge: true },
      { name: 'Salt & Pepper', qty: 'to taste', fromFridge: false },
    ],
    steps: [
      { instruction: 'Preheat grill/broiler to high.', timerSeconds: null },
      { instruction: 'Whisk eggs with milk, salt, and pepper.', timerSeconds: null },
      { instruction: 'Heat an oven-safe pan, add spinach and wilt for 1 minute.', timerSeconds: 60 },
      { instruction: 'Add leftover pasta and spread evenly.', timerSeconds: null },
      { instruction: 'Pour egg mixture over and top with grated cheese.', timerSeconds: null },
      { instruction: 'Cook on medium for 5 minutes until edges set, then grill for 3 minutes until golden.', timerSeconds: 300 },
    ],
    nutrition: { calories: 370, protein: 22, carbs: 34, fat: 16 },
  },
  {
    id: 'r14',
    name: 'Watermelon Strawberry Cooler',
    emoji: '🍉',
    time: '5 min',
    difficulty: 'Easy',
    servings: 2,
    description: 'Refreshing blended drink using cut watermelon, strawberries, and yogurt.',
    usesExpiring: true,
    cuisineType: 'American',
    ingredients: [
      { name: 'Cut Watermelon', qty: '1 container', fromFridge: true },
      { name: 'Strawberries', qty: '100 g', fromFridge: true },
      { name: 'Greek Yogurt Cup', qty: '1 cup', fromFridge: true },
      { name: 'Whole Milk', qty: '100 ml', fromFridge: true },
      { name: 'Honey', qty: '1 tsp', fromFridge: false },
    ],
    steps: [
      { instruction: 'Add watermelon, strawberries, yogurt, and milk to a blender.', timerSeconds: null },
      { instruction: 'Blend until smooth, about 30 seconds.', timerSeconds: 30 },
      { instruction: 'Taste and add honey if needed.', timerSeconds: null },
      { instruction: 'Pour over ice and serve immediately.', timerSeconds: null },
    ],
    nutrition: { calories: 160, protein: 6, carbs: 30, fat: 2 },
  },
  {
    id: 'r15',
    name: 'Salmon Basil Pasta',
    emoji: '🐟',
    time: '25 min',
    difficulty: 'Medium',
    servings: 2,
    description: 'Elegant pasta with flaked salmon, fresh basil, and a light olive oil sauce.',
    usesExpiring: true,
    cuisineType: 'Italian',
    ingredients: [
      { name: 'Salmon Fillet', qty: '1 pc', fromFridge: true },
      { name: 'Pasta', qty: '250 g', fromFridge: true },
      { name: 'Fresh Basil', qty: '1 bunch', fromFridge: true },
      { name: 'Olive Oil', qty: '3 tbsp', fromFridge: true },
      { name: 'Cheddar Cheese', qty: '40 g', fromFridge: true },
      { name: 'Garlic', qty: '2 cloves', fromFridge: false },
      { name: 'Salt & Pepper', qty: 'to taste', fromFridge: false },
    ],
    steps: [
      { instruction: 'Cook pasta in salted boiling water until al dente.', timerSeconds: 600 },
      { instruction: 'Season salmon and pan-fry in olive oil for 4 minutes each side.', timerSeconds: 240 },
      { instruction: 'Rest salmon for 3 minutes then flake into chunks.', timerSeconds: 180 },
      { instruction: 'In the same pan, gently warm garlic in remaining oil.', timerSeconds: 60 },
      { instruction: 'Toss drained pasta in the garlic oil with a splash of pasta water.', timerSeconds: null },
      { instruction: 'Fold in salmon, torn basil, and grated cheese. Serve immediately.', timerSeconds: null },
    ],
    nutrition: { calories: 520, protein: 36, carbs: 52, fat: 18 },
  },
];

export const QUICK_MEAL_OPTIONS = [
  { name: 'Scrambled Eggs', emoji: '🥚', time: '10 min' },
  { name: 'Toast & Avocado', emoji: '🥑', time: '5 min' },
  { name: 'Greek Yogurt Bowl', emoji: '🥄', time: '5 min' },
  { name: 'Chicken Stir Fry', emoji: '🍗', time: '25 min' },
  { name: 'Pasta Carbonara', emoji: '🍝', time: '20 min' },
  { name: 'Salmon & Rice', emoji: '🐟', time: '30 min' },
  { name: 'Spinach Salad', emoji: '🥗', time: '10 min' },
  { name: 'Banana Pancakes', emoji: '🥞', time: '15 min' },
  { name: 'Cheese Sandwich', emoji: '🧀', time: '5 min' },
  { name: 'Rice Bowl', emoji: '🍚', time: '20 min' },
];

export const INITIAL_HEALTH_DATA = {
  dailyCalorieGoal: 2000,
  today: {
    calories: 1240,
    meals: [
      { id: 'm1', name: 'Greek Yogurt Bowl', emoji: '🥄', time: '8:00 AM', calories: 320 },
      { id: 'm2', name: 'Turkey Avocado Sandwich', emoji: '🥪', time: '12:30 PM', calories: 480 },
      { id: 'm3', name: 'Strawberry Smoothie', emoji: '🍓', time: '3:00 PM', calories: 210 },
      { id: 'm4', name: 'Cheese & Spinach Omelette', emoji: '🍳', time: '6:30 PM', calories: 230 },
    ],
  },
  daily: [
    { day: '27', calories: 1920 }, { day: '28', calories: 1650 }, { day: '1',  calories: 2100 },
    { day: '2',  calories: 1780 }, { day: '3',  calories: 1850 }, { day: '4',  calories: 2200 },
    { day: '5',  calories: 1600 }, { day: '6',  calories: 1750 }, { day: '7',  calories: 2300 },
    { day: '8',  calories: 1900 }, { day: '9',  calories: 1820 }, { day: '10', calories: 2050 },
    { day: '11', calories: 1700 }, { day: '12', calories: 1980 }, { day: '13', calories: 2150 },
    { day: '14', calories: 1550 }, { day: '15', calories: 1870 }, { day: '16', calories: 2080 },
    { day: '17', calories: 1760 }, { day: '18', calories: 1930 }, { day: '19', calories: 2220 },
    { day: '20', calories: 1640 }, { day: '21', calories: 1810 }, { day: '22', calories: 2040 },
    { day: '23', calories: 1720 }, { day: '24', calories: 1960 }, { day: '25', calories: 2180 },
    { day: '26', calories: 1580 }, { day: '27', calories: 2050 }, { day: '28', calories: 1240 },
  ],
};

export const MOCK_RECEIPT_ITEMS = [
  { name: 'Chicken Thighs', qty: 1, unit: 'kg', expiryDays: 3, emoji: '🍗', category: 'Meat', selected: true },
  { name: 'Baby Spinach', qty: 1, unit: 'bag', expiryDays: 5, emoji: '🥬', category: 'Produce', selected: true },
  { name: 'Almond Milk', qty: 1, unit: 'L', expiryDays: 10, emoji: '🥛', category: 'Dairy', selected: true },
  { name: 'Sourdough Loaf', qty: 1, unit: 'pc', expiryDays: 5, emoji: '🍞', category: 'Bakery', selected: true },
  { name: 'Blueberries', qty: 1, unit: 'punnet', expiryDays: 4, emoji: '🫐', category: 'Produce', selected: true },
  { name: 'Pasta Sauce', qty: 1, unit: 'jar', expiryDays: 180, emoji: '🍅', category: 'Condiments', selected: true },
];
